InsecureFastScrypt = true # Default
RootDir = '~/.chainlink' # Default
ShutdownGracePeriod = '5s' # Default

[Log]
Level = 'info'

[WebServer]
AllowOrigins = '\*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '2024'
LinkContractAddress = '0x3f5CBA916576A6Ce277dA066fD210D895a595F71' # Example
MinContractPayment = '0.1 link'



[[EVM.Nodes]]
Name = 'node00'
WSURL = 'ws://192.168.3.66:8546'
HTTPURL = 'http://192.168.3.66:8000'

